### ISSUE TITLE
Consider dropping support for pegcoffee

### ISSUE THREAD

**Issue by sertonix** [pulsar-edit/language-pegjs#2]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

This package includes syntax highlighting for [`pegcoffee`](https://github.com/ttilley/pegcoffee).
I would suggest removing that.

### What benefits does this feature provide?

Since the repo was last updated 10 years ago and never really had a lot of development it seems useless to me to maintain highlighting for it. So it would ease development (a bit).

### Further ideas

Maybe this package could be extended to include multiple peg based languages or syntax describing languages. This may help to make the development more active.

**Comment by confused-Techie** [comment]
Personally I wouldn't want to delete it. Although it may make sense to put it in it's own package? Unless it adds a lot to the startup time, or size of the package, I wouldn't be to worried, even if supporting it at all is extremely niche. Would you think it makes more sense as it's own package? Or as being a part of this one still

**Comment by sertonix** [comment]
Then as part of this one would make more sense.
